# SF Salaries Exercise

Welcome to a quick exercise for you to practice your pandas skills! We will be using the [SF Salaries Dataset](https://www.kaggle.com/kaggle/sf-salaries) from Kaggle! Just follow along and complete the tasks outlined in bold below. The tasks will get harder and harder as you go along.

**Import pandas as pd.**

In [ ]:
import pandas as pd

**Read Salaries.csv as a dataframe called sal.**

In [ ]:
sal = pd.read_csv("/Salaries.csv")

/tmp/ipython-input-27886606.py:1: DtypeWarning: Columns (3,4,5,6,12) have mixed types. Specify dtype option on import or set low_memory=False.
  sal = pd.read_csv("/Salaries.csv")

**Check the head of the DataFrame.**

In [ ]:
sal.head(5)

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.0,400184.25,NaN,567595.43,567595.43,2011,NaN,San Francisco,NaN
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011,NaN,San Francisco,NaN
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.6,NaN,335279.91,335279.91,2011,NaN,San Francisco,NaN
3,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.0,56120.71,198306.9,NaN,332343.61,332343.61,2011,NaN,San Francisco,NaN
4,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.6,9737.0,182234.59,NaN,326373.19,326373.19,2011,NaN,San Francisco,NaN

**Use the .info() method to find out how many entries there are.**

In [ ]:
sal.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Id                148654 non-null  int64
 1   EmployeeName      148654 non-null  object
 2   JobTitle          148654 non-null  object
 3   BasePay           148049 non-null  object
 4   OvertimePay       148654 non-null  object
 5   OtherPay          148654 non-null  object
 6   Benefits          112495 non-null  object
 7   TotalPay          148654 non-null  float64
 8   TotalPayBenefits  148654 non-null  float64
 9   Year              148654 non-null  int64
 10  Notes             0 non-null       float64
 11  Agency            148654 non-null  object
 12  Status            38119 non-null   object
dtypes: float64(3), int64(2), object(8)
memory usage: 14.7+ MB

**What is the average BasePay ?**

In [ ]:
sal["BasePay"] = pd.to_numeric(sal["BasePay"], errors="coerce")
bp = sal["BasePay"].mean()
print(bp)

66325.4488404877

**What is the highest amount of OvertimePay in the dataset ?**

In [ ]:
sal["OvertimePay"] = pd.to_numeric(sal["OvertimePay"], errors="coerce")
max = sal["OvertimePay"].max()
print(max)

245131.88

**What is the job title of  JOSEPH DRISCOLL ? Note: Use all caps, otherwise you may get an answer that doesn't match up (there is also a lowercase Joseph Driscoll).**

In [ ]:
t = sal.loc[sal["EmployeeName"] == "JOSEPH DRISCOLL", "JobTitle"].iloc[0]
print(t)

CAPTAIN, FIRE SUPPRESSION

**How much does JOSEPH DRISCOLL make (including benefits)?**

In [ ]:
t = sal.loc[sal["EmployeeName"] == "JOSEPH DRISCOLL", "TotalPayBenefits"].iloc[0]
print(t)

270324.91

**What is the name of highest paid person (including benefits)?**

In [ ]:
sal["TotalPayBenefits"] = pd.to_numeric(sal["TotalPayBenefits"], errors="coerce")
max = sal["TotalPayBenefits"].max()
sal.loc[sal["TotalPayBenefits"] == max, "EmployeeName"].iloc[0]

'NATHANIEL FORD'

**What is the name of lowest paid person (including benefits)? Do you notice something strange about how much he or she is paid?**

In [ ]:
sal["TotalPayBenefits"] = pd.to_numeric(sal["TotalPayBenefits"], errors="coerce")
max = sal["TotalPayBenefits"].min()
sal.loc[sal["TotalPayBenefits"] == max, "EmployeeName"].iloc[0]

#print(max)
#he's paid negative? what?

#sal.loc[sal["TotalPayBenefits"] == max]
#his salary is zero and otherpay is negative. ig he's unpaid and broke a vase or something?

'Joe Lopez'

**What was the average (mean) BasePay of all employees per year? (2011-2014) ?**

In [ ]:
print(sal.groupby("Year")["BasePay"].mean())

Year
2011    63595.956517
2012    65436.406857
2013    69630.030216
2014    66564.421924
Name: BasePay, dtype: float64

**How many unique job titles are there?**

In [ ]:
sal["JobTitle"].nunique()

2159

**What are the top 5 most common jobs?**

In [ ]:
print(sal["JobTitle"].value_counts().head(5))

JobTitle
Transit Operator                7036
Special Nurse                   4389
Registered Nurse                3736
Public Svc Aide-Public Works    2518
Police Officer 3                2421
Name: count, dtype: int64

**How many Job Titles were represented by only one person in 2013? (e.g. Job Titles with only one occurence in 2013?)**

In [ ]:
t = sal.loc[sal["Year"] == 2013, "JobTitle"].value_counts()
print(t[t==1].count())

202

**How many people have the word Chief in their job title? (This is pretty tricky)**

In [105]:
#IDK which cases I'm missing but the answers are not matching with the question

t = 0
for i in sal["JobTitle"]:
  if "Chief " in i :
    t = t + 1
  elif "Chief," in i:
    t = t + 1
  elif i.endswith("Chief"):
    t = t + 1



print(t)

423

In [ ]:
t = list(sal["JobTitle"].unique())

for i in t:
  if "Chief" in i:
    print(i)

Chief of Police
Chief, Fire Department
Battlion Chief, Fire Suppressi
Assistant Deputy Chief 2
Deputy Chief 3
Emergency Medical Svcs Chief
Chief Atty1 (Civil & Criminal)
Chief Adult Probation Officer
Assistant Chief Attorney 2
Assistant Chief Attorney 1
Chief Deputy Sheriff
Chief Stationary Engineer
Chief Water Service Inspector
Chief Building Inspector
Chief Plumbing Inspector
Chief Electrical Inspector
Chief Housing Inspector
Chief Dep Adlt Prob Of (SFERS)
Chief Fire Alarm Dispatcher
Chief Surveyor
Chief Nursery Specialist
Chief Dietitian
Chief Clerk
Chief Preparator
Chief Telephone Operator
Chief Deputy Adlt Probation Of
Battalion Chief, Fire Suppress
Chief Investment Officer
Chief Forensic Toxicologist

**Is there a correlation between length of the Job Title string and Salary?**

                  title_len  TotalPayBenefits
title_len          1.000000         -0.036878
TotalPayBenefits  -0.036878          1.000000

# Great Job!